### ISSUE TITLE
Last month checklist

### ISSUE THREAD

**Issue by quentinberder** [jsconfcn/ShenJS#26]
We need to make sure of the following:
- [x] Number of seats in the main room
- [x] Usage of annex rooms
- [ ] Wifi name + password and capacity
- [x] Tables for sponsors and 
- [x] Floor-plan (see #25 )
- [x] Number of chairs
- [ ] Equipment for the after party (sound system, bar, table, entertainments, fridge, etc.)
- [x] Tickets support
- [x] Security (volunteers?)

**Comment by bencrox** [comment]
Shall I follow this up, in this 3 days ?

**Comment by clairesheng** [comment]
@bencrox Thanks. I am following up with the venue. Will let you know when need your help.

**Comment by clairesheng** [comment]
- Number of seats in the main room: 900 seats maximum
- Usage of annex rooms: 1 dressing room & 1 VIP reception room
- Wifi name + password and capacity: We can set by ourselves. We bring 2 router and cable.
- Tables for sponsors：table size 2x1m. 17 tables to set up. Asking for the floor plan.
- Equipment for the after party (sound system, bar, table, entertainments, fridge, etc.)
  - Fridge: need to buy beer. 
  - Sound system: restaurant with open air has no sound system, need to rent the equipment. It involves additional cost, cabling, examination...so checking right now.
- The venue can set up the desks and chairs as we require. 
- Tickets support: Every participant has receive a message with check-in code. We scan their QR code through ipad or phone.

**Comment by quentinberder** [comment]
- What is the app we should use for the tickets?
